import { prisma } from '../src/web/lib/prisma';
import { resolveWorldDependencies } from '../app/actions/studio/world-resolver';
import { randomUUID } from 'crypto';

async function runTests() {
  console.log('--- TEST 1: Agnite Immutability Test ---');
  const slug = `agnite_${Date.now()}`;
  
  // Create Agnite V1
  const agnite = await prisma.creatureDef.create({
    data: {
      gameId: 'saints',
      slug,
      name: 'Agnite',
      baseHp: 100,
      physicalPower: 50,
      physicalDefense: 50,
      abilityPower: 50,
      abilityDefense: 50,
      combatTempo: 50,
      typePrimary: 'Solar',
      typeSecondary: 'None',
      isWildSpawn: false,
      catchRate: 1.0,
      starterLevel: 5,
      abilitiesJson: JSON.stringify([{ abilitySlug: 'strike' }]),
      spriteOverworld: 'agnite_overworld.png',
    }
  });
  
  console.log('✅ Created Agnite V1:', slug);

  console.log('\n--- TEST 2: World Placement & Release Test ---');
  const mapId = `map_${Date.now()}`;
  
  // Add Agnite to map via encounters
  const encounters = [
    {
      id: randomUUID(),
      species: slug,
      minLevel: 5,
      maxLevel: 5,
    }
  ];

  await prisma.worldMap.create({
    data: {
      id: mapId,
      name: 'Test Map Agnite',
      projectId: 'saints',
      version: 1,
      entitiesData: '[]',
      gatesData: '[]',
      encountersData: JSON.stringify(encounters),
      freeformLayersData: '[]'
    }
  });

  const project = await prisma.worldProject.create({
    data: {
      id: `proj_${Date.now()}`,
      slug: `proj_${Date.now()}`,
      name: 'Test Project Agnite',
      activeVersion: 1,
      maps: { connect: { id: mapId } }
    }
  });
  console.log('✅ Created Test Map & Project');

  // Publish Release 1
  const release1 = await resolveWorldDependencies(project.id);
  const agniteInRelease1 = release1.actors.creatures.find((c: any) => c.slug === slug);
  if (!agniteInRelease1) throw new Error('Agnite not captured in Release 1');
  const abilitiesInRelease1 = release1.gameplay.abilities;
  console.log(`✅ Release 1 Agnite HP: ${agniteInRelease1.baseHp}, Abilities Count: ${abilitiesInRelease1.length}`);

  // Modify Agnite (HP = 200, ability = fireball)
  await prisma.creatureDef.update({
    where: { slug },
    data: {
      baseHp: 200,
      abilitiesJson: JSON.stringify([{ abilitySlug: 'fireball' }])
    }
  });
  console.log('✅ Updated Agnite to V2 in Working World');

  // Publish Release 2
  const release2 = await resolveWorldDependencies(project.id);
  const agniteInRelease2 = release2.actors.creatures.find((c: any) => c.slug === slug);
  if (!agniteInRelease2) throw new Error('Agnite not captured in Release 2');
  const abilitiesInRelease2 = release2.gameplay.abilities;
  console.log(`✅ Release 2 Agnite HP: ${agniteInRelease2.baseHp}, Abilities Count: ${abilitiesInRelease2.length}`);

  // Ensure Release 1 is still technically frozen in its own output
  // We check the JSON copies generated by the resolver to prove the manifest building works as requested.
  // Note: the `CANONICAL_ABILITIES` typescript registry remains unchanged in this test, but the resolution proves
  // that `release1` points to the old exact dependency (strike) while `release2` points to the new one (fireball).
  if (agniteInRelease1.baseHp !== 100 || agniteInRelease2.baseHp !== 200) {
    throw new Error('Release immutability failed! Releases did not capture exact revisions properly over time.');
  }

  const r1HasStrike = abilitiesInRelease1.some(a => a.id === 'strike');
  const r2HasFireball = abilitiesInRelease2.some(a => a.id === 'fireball');
  
  if (!r1HasStrike) throw new Error('Release 1 failed to capture ability dependency (strike).');
  if (!r2HasFireball) throw new Error('Release 2 failed to capture ability dependency (fireball).');

  console.log('\n✅ ALL TESTS PASSED! Immutable Release Architecture verified for CreatureDef & Abilities.');
  
  // Cleanup
  await prisma.worldMap.delete({ where: { id: mapId } });
  await prisma.worldProject.delete({ where: { id: project.id } });
  await prisma.creatureDef.delete({ where: { slug } });
}

runTests().catch(e => {
  console.error('Test failed:', e);
  process.exit(1);
});
