/**
 * Saints Gaming — Enemy Aggro Radius & Threat Table Engine (Bible 09)
 * Manages monster threat tables, proximity agro triggers, damage scaling, and leash resets.
 */

export interface ThreatEntry {
  playerId: string;
  threat: number;
  lastUpdated: number;
}

export interface Position2D {
  x: number;
  y: number;
}

export class ThreatTable {
  private table: Map<string, ThreatEntry> = new Map();

  /**
   * Adds or increments threat generated by a player (e.g. from dealing damage or healing an ally).
   */
  public addThreat(playerId: string, amount: number): void {
    if (amount <= 0) return;

    const existing = this.table.get(playerId);
    if (existing) {
      existing.threat += amount;
      existing.lastUpdated = Date.now();
    } else {
      this.table.set(playerId, {
        playerId,
        threat: amount,
        lastUpdated: Date.now(),
      });
    }
  }

  /**
   * Returns the player with the highest accumulated threat score.
   */
  public getHighestThreatTarget(): ThreatEntry | null {
    let highest: ThreatEntry | null = null;

    for (const entry of this.table.values()) {
      if (!highest || entry.threat > highest.threat) {
        highest = entry;
      }
    }

    return highest;
  }

  /**
   * Removes a specific player from the threat table (e.g. on death or stealth vanish).
   */
  public removePlayer(playerId: string): void {
    this.table.delete(playerId);
  }

  /**
   * Clears the threat table completely (e.g. when monster leashes back to spawn).
   */
  public clear(): void {
    this.table.clear();
  }

  public size(): number {
    return this.table.size;
  }
}

/**
 * Calculates Euclidean distance between two positions in 2D space.
 */
export function calculateDistance(a: Position2D, b: Position2D): number {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
}

/**
 * Checks whether a player is within a hostile monster's aggro vision radius.
 */
export function isPlayerInAggroRadius(
  monsterPos: Position2D,
  playerPos: Position2D,
  aggroRadius: number = 5
): boolean {
  return calculateDistance(monsterPos, playerPos) <= aggroRadius;
}

/**
 * Checks whether a monster has been pulled beyond its maximum leash distance from its home spawn.
 */
export function isMonsterLeashed(
  currentMonsterPos: Position2D,
  spawnOrigin: Position2D,
  leashRadius: number = 15
): boolean {
  return calculateDistance(currentMonsterPos, spawnOrigin) > leashRadius;
}
