"use client";

import { useState, useMemo } from "react";
import { Button } from "@/shared/ui/button";
import { Input } from "@/shared/ui/input";
import { Label } from "@/shared/ui/label";
import { Badge } from "@/shared/ui/badge";
import { Switch } from "@/shared/ui/switch";
import { Textarea } from "@/shared/ui/textarea";
import {
  Bot,
  ShieldCheck,
  ShieldAlert,
  Copy,
  Download,
  Plus,
  Trash2,
  Check,
  Search,
  CheckCircle2,
  AlertCircle,
  FileCode,
  Sparkles,
} from "lucide-react";

interface RobotsStudioTabProps {
  initialCustomRules: string;
  initialBlockAi: string;
  baseUrl: string;
  onChangeField?: (field: string, value: string) => void;
}

const DEFAULT_DISALLOWS = [
  "/admin/",
  "/ucp/",
  "/profile/",
  "/api/",
  "/forum/*/new",
  "/reset-password",
  "/forgot-password",
];

const AI_BOTS = [
  { name: "GPTBot", desc: "OpenAI crawler for web indexing and model training" },
  { name: "ChatGPT-User", desc: "OpenAI user-invoked live web browsing requests" },
  { name: "ClaudeBot", desc: "Anthropic crawler for training Claude LLMs" },
  { name: "anthropic-ai", desc: "Anthropic web data extraction crawler" },
  { name: "PerplexityBot", desc: "Perplexity AI search engine crawler" },
  { name: "CCBot", desc: "Common Crawl foundational open-web dataset bot" },
  { name: "Google-Extended", desc: "Google Gemini training crawler control" },
];

export function RobotsStudioTab({
  initialCustomRules,
  initialBlockAi,
  baseUrl,
  onChangeField,
}: RobotsStudioTabProps) {
  const [copied, setCopied] = useState(false);
  const [blockAi, setBlockAi] = useState(initialBlockAi === "true");
  const [disallowPaths, setDisallowPaths] = useState<string[]>(() => {
    if (initialCustomRules) {
      try {
        const parsed = JSON.parse(initialCustomRules);
        if (Array.isArray(parsed) && parsed.length > 0) return parsed;
      } catch {
        // Not JSON, use defaults
      }
    }
    return DEFAULT_DISALLOWS;
  });

  const [newPath, setNewPath] = useState("");
  const [testUrlPath, setTestUrlPath] = useState("/admin/users");

  // Sync state up
  const updateDisallows = (newPaths: string[]) => {
    setDisallowPaths(newPaths);
    if (onChangeField) {
      onChangeField("SEO_ROBOTS_CUSTOM", JSON.stringify(newPaths));
    }
  };

  const handleToggleBlockAi = (checked: boolean) => {
    setBlockAi(checked);
    if (onChangeField) {
      onChangeField("SEO_BLOCK_AI_CRAWLERS", checked ? "true" : "false");
    }
  };

  const addPath = () => {
    const trimmed = newPath.trim();
    if (!trimmed) return;
    const formatted = trimmed.startsWith("/") ? trimmed : `/${trimmed}`;
    if (!disallowPaths.includes(formatted)) {
      const updated = [...disallowPaths, formatted];
      updateDisallows(updated);
    }
    setNewPath("");
  };

  const removePath = (pathToRemove: string) => {
    const updated = disallowPaths.filter((p) => p !== pathToRemove);
    updateDisallows(updated);
  };

  const resetToDefaults = () => {
    updateDisallows(DEFAULT_DISALLOWS);
  };

  // Generate generated robots.txt plain text output
  const generatedRobotsTxt = useMemo(() => {
    const cleanBaseUrl = baseUrl.replace(/\/$/, "");
    const lines: string[] = [];

    lines.push("# ==========================================================================");
    lines.push("# Saints Gaming — robots.txt");
    lines.push("# Automatically generated by Admin SEO Management Suite");
    lines.push("# ==========================================================================");
    lines.push("");

    // Section 1: Standard Search Engine Bots
    lines.push("# Standard Search Engine Crawlers");
    lines.push("User-agent: *");
    lines.push("Allow: /");
    disallowPaths.forEach((path) => {
      lines.push(`Disallow: ${path}`);
    });
    lines.push("");

    // Section 2: AI & LLM Crawlers
    if (blockAi) {
      lines.push("# Block AI & LLM Training Crawlers");
      AI_BOTS.forEach((bot) => {
        lines.push(`User-agent: ${bot.name}`);
        lines.push("Disallow: /");
        lines.push("");
      });
    } else {
      lines.push("# AI Crawlers: Allowed (Following general User-agent rules)");
    }

    // Section 3: Sitemap Declaration
    lines.push("# Sitemap Index");
    lines.push(`Sitemap: ${cleanBaseUrl}/sitemap.xml`);

    return lines.join("\n");
  }, [baseUrl, disallowPaths, blockAi]);

  // Real-time Path Tester
  const testResult = useMemo(() => {
    const path = testUrlPath.trim().startsWith("/") ? testUrlPath.trim() : `/${testUrlPath.trim()}`;
    if (!path) return null;

    for (const rule of disallowPaths) {
      if (rule.endsWith("/")) {
        if (path.startsWith(rule) || path === rule.slice(0, -1)) {
          return { allowed: false, matchedRule: rule };
        }
      } else if (rule.includes("*")) {
        const regex = new RegExp("^" + rule.replace(/\*/g, ".*") + "$");
        if (regex.test(path)) {
          return { allowed: false, matchedRule: rule };
        }
      } else {
        if (path === rule || path.startsWith(rule + "/")) {
          return { allowed: false, matchedRule: rule };
        }
      }
    }
    return { allowed: true, matchedRule: "Allow: /" };
  }, [testUrlPath, disallowPaths]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedRobotsTxt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generatedRobotsTxt], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "robots.txt";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8">
      {/* Overview Banner */}
      <div className="bg-card/40 border border-border/50 rounded-xl p-5 sg-glass flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Bot className="w-4 h-4 text-primary" />
            <h3 className="text-base font-bold text-foreground">Robots.txt Rule Manager &amp; Bot Studio</h3>
          </div>
          <p className="text-xs text-muted-foreground">
            Control search engine crawler indexing boundaries, block unauthorized AI scrapers, and preview live directives.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button type="button" size="sm" variant="outline" onClick={handleCopy} className="text-xs gap-1.5">
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? "Copied!" : "Copy robots.txt"}
          </Button>
          <Button type="button" size="sm" variant="default" onClick={handleDownload} className="text-xs gap-1.5">
            <Download className="w-3.5 h-3.5" />
            Download robots.txt
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Rules & AI Crawler Toggles */}
        <div className="lg:col-span-6 space-y-6">
          {/* Disallow Rules Box */}
          <div className="bg-card/40 border border-border/50 rounded-xl p-5 sg-glass space-y-4">
            <div className="flex items-center justify-between border-b border-border/40 pb-3">
              <div>
                <h4 className="text-sm font-bold text-foreground">Disallowed Crawl Paths</h4>
                <p className="text-xs text-muted-foreground">Directories search engines are forbidden from indexing.</p>
              </div>
              <Button type="button" size="sm" variant="ghost" onClick={resetToDefaults} className="text-xs text-muted-foreground hover:text-foreground">
                Reset Defaults
              </Button>
            </div>

            {/* Add New Rule */}
            <div className="flex gap-2">
              <Input
                value={newPath}
                onChange={(e) => setNewPath(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    addPath();
                  }
                }}
                placeholder="e.g. /private/ or /staff/*"
                className="text-xs font-mono"
              />
              <Button type="button" size="sm" onClick={addPath} className="text-xs gap-1">
                <Plus className="w-3.5 h-3.5" />
                Add
              </Button>
            </div>

            {/* Path List */}
            <div className="space-y-1.5 max-h-56 overflow-y-auto pr-1">
              {disallowPaths.map((p, i) => (
                <div
                  key={i}
                  className="flex items-center justify-between px-3 py-1.5 rounded-lg bg-secondary/30 border border-border/40 text-xs font-mono"
                >
                  <span className="text-rose-400 font-medium">Disallow: {p}</span>
                  <button
                    type="button"
                    onClick={() => removePath(p)}
                    className="text-muted-foreground hover:text-rose-400 p-1 transition-colors"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>
          </div>

          {/* AI Scraper & LLM Crawler Blocker */}
          <div className="bg-card/40 border border-border/50 rounded-xl p-5 sg-glass space-y-4">
            <div className="flex items-center justify-between border-b border-border/40 pb-3">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-purple-400" />
                <div>
                  <h4 className="text-sm font-bold text-foreground">AI &amp; LLM Crawler Control</h4>
                  <p className="text-xs text-muted-foreground">Block AI bots from harvesting forum posts and game lore.</p>
                </div>
              </div>
              <Switch checked={blockAi} onCheckedChange={handleToggleBlockAi} />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
              {AI_BOTS.map((bot, i) => (
                <div
                  key={i}
                  className={`p-2.5 rounded-lg border transition-all ${
                    blockAi
                      ? "bg-rose-500/10 border-rose-500/20 text-rose-300"
                      : "bg-secondary/20 border-border/30 text-muted-foreground"
                  }`}
                >
                  <div className="font-semibold flex items-center justify-between font-mono">
                    <span>{bot.name}</span>
                    <Badge variant="outline" className={`text-[10px] ${blockAi ? "bg-rose-500/20 text-rose-300 border-rose-500/40" : "bg-emerald-500/10 text-emerald-400 border-emerald-500/30"}`}>
                      {blockAi ? "Blocked" : "Allowed"}
                    </Badge>
                  </div>
                  <div className="text-[11px] text-muted-foreground mt-0.5 leading-snug">{bot.desc}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Live Interactive URL Tester */}
          <div className="bg-card/40 border border-border/50 rounded-xl p-5 sg-glass space-y-3">
            <div className="flex items-center gap-2">
              <Search className="w-4 h-4 text-primary" />
              <h4 className="text-sm font-bold text-foreground">Test URL Against robots.txt</h4>
            </div>

            <div className="flex gap-2">
              <Input
                value={testUrlPath}
                onChange={(e) => setTestUrlPath(e.target.value)}
                placeholder="Enter path to test, e.g. /admin/users or /news/patch"
                className="text-xs font-mono"
              />
            </div>

            {testResult && (
              <div
                className={`flex items-center justify-between p-3 rounded-lg border text-xs ${
                  testResult.allowed
                    ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-400"
                    : "bg-rose-500/10 border-rose-500/30 text-rose-400"
                }`}
              >
                <div className="flex items-center gap-2 font-medium">
                  {testResult.allowed ? (
                    <CheckCircle2 className="w-4 h-4 shrink-0" />
                  ) : (
                    <AlertCircle className="w-4 h-4 shrink-0" />
                  )}
                  <span>
                    {testResult.allowed
                      ? `CRAWL ALLOWED — Search engines can index '${testUrlPath}'`
                      : `BLOCKED — Matched rule '${testResult.matchedRule}'`}
                  </span>
                </div>
                <Badge variant="outline" className={testResult.allowed ? "border-emerald-500/40 text-emerald-300" : "border-rose-500/40 text-rose-300"}>
                  {testResult.allowed ? "200 INDEXABLE" : "DISALLOWED"}
                </Badge>
              </div>
            )}
          </div>
        </div>

        {/* Right Column: Live Output Viewer */}
        <div className="lg:col-span-6 space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
              <FileCode className="w-4 h-4 text-primary" />
              Live Generated robots.txt Preview
            </span>
            <span className="text-[11px] text-muted-foreground font-mono">
              GET /robots.txt
            </span>
          </div>

          <div className="relative bg-zinc-950/90 border border-zinc-800 rounded-xl p-4 font-mono text-xs text-zinc-300 overflow-x-auto shadow-xl h-[480px]">
            <pre className="leading-relaxed whitespace-pre font-mono selection:bg-primary/30">
              {generatedRobotsTxt}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
