/**
 * Saints Gaming — Character Select Admin Capability Registry
 * Consolidated Matrix mapping 38 administrative and operational game controls.
 */

export type AdminSectionId =
  | 'overview'
  | 'realm'
  | 'camera'
  | 'releases'
  | 'maintenance'
  | 'diagnostics'
  | 'staff';

export interface AdminCapability {
  id: string;
  label: string;
  section: AdminSectionId;
  minPermission: number; // 200 = Mod, 400 = Admin, 1000 = Developer
  mode: 'native' | 'link' | 'web-only';
  isDestructive?: boolean;
  toolbarSlot?: string;
  footerSlot?: string;
  linkUrl?: string;
  description?: string;
}

export const ADMIN_SECTIONS: { id: AdminSectionId; label: string; subtitle: string; minPermission: number }[] = [
  { id: 'overview', label: 'Overview', subtitle: 'Overview', minPermission: 200 },
  { id: 'realm', label: 'Realm', subtitle: 'Realm Control', minPermission: 200 },
  { id: 'camera', label: 'Camera', subtitle: 'Camera Policy', minPermission: 400 },
  { id: 'releases', label: 'Releases', subtitle: 'Release & Version', minPermission: 400 },
  { id: 'maintenance', label: 'Maintenance', subtitle: 'Maintenance', minPermission: 1000 },
  { id: 'diagnostics', label: 'Diagnostics', subtitle: 'Diagnostics', minPermission: 200 },
  { id: 'staff', label: 'Staff', subtitle: 'Staff Tools', minPermission: 200 },
];

export const ADMIN_CAPABILITIES: AdminCapability[] = [
  // Overview
  {
    id: 'cmd-status-summary',
    label: 'Command Center Status Summary',
    section: 'overview',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'Refresh / View',
    footerSlot: 'Alerts / Quick Actions',
    description: 'High-level snapshot of players, world maps, tickets, and active alerts.',
  },
  {
    id: 'recent-operator-activity',
    label: 'Recent Operator Activity',
    section: 'overview',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'View',
    footerSlot: 'Alerts / Open Full Admin',
    description: 'Chronological audit trail of privileged mutations and actions.',
  },
  {
    id: 'lobby-gateway-status',
    label: 'Lobby & Gateway Live Status',
    section: 'overview',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'Refresh / Filters',
    footerSlot: 'Last Check',
    description: 'Destination Go MMO heartbeat and TS GameEngine cluster state.',
  },
  {
    id: 'player-occupancy-overview',
    label: 'Player Occupancy & Capacity',
    section: 'overview',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'View',
    footerSlot: 'Players',
    description: 'Real-time player presence counts vs maximum configured limit.',
  },
  {
    id: 'runtime-env-display',
    label: 'Runtime Environment Display',
    section: 'overview',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'View',
    footerSlot: 'Environment',
    description: 'Current hosting environment (development, staging, docker, production).',
  },

  // Realm Control
  {
    id: 'realm-online-status',
    label: 'Realm Online/Offline Status',
    section: 'realm',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'View',
    footerSlot: 'Live State',
    description: 'Live availability state of the game realm.',
  },
  {
    id: 'start-realm',
    label: 'Start Realm',
    section: 'realm',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'Actions',
    footerSlot: 'Start Realm',
    description: 'Brings the game realm online for general player connections.',
  },
  {
    id: 'stop-realm',
    label: 'Stop Realm',
    section: 'realm',
    minPermission: 400,
    mode: 'native',
    isDestructive: true,
    toolbarSlot: 'Actions / Safety',
    footerSlot: 'Stop Realm',
    description: 'Takes the game realm offline with graceful connection teardown.',
  },
  {
    id: 'reset-dev-override',
    label: 'Reset Dev / Server Override',
    section: 'realm',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'Safety',
    footerSlot: 'Live State / Reset',
    description: 'Clears manual server state overrides and re-binds to gateway heartbeat.',
  },

  // Camera Policy
  {
    id: 'default-camera-style',
    label: 'Default Camera Style',
    section: 'camera',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'File / View',
    footerSlot: 'Policy State',
    description: 'Global presentation view policy (Isometric, Follow 45°, Top-down, Free Orbit).',
  },
  {
    id: 'camera-smoothing-defaults',
    label: 'Camera Smoothing Defaults',
    section: 'camera',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'View / Presets',
    footerSlot: 'Policy State',
    description: 'Global interpolation and damping factors for player camera follow.',
  },
  {
    id: 'border-clamping-defaults',
    label: 'Border Clamping Defaults',
    section: 'camera',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'View / Presets',
    footerSlot: 'Policy State',
    description: 'Constrains viewport camera to map world bounds without void bleed.',
  },
  {
    id: 'vignette-presentation-rules',
    label: 'Vignette & Atmospheric Rules',
    section: 'camera',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'View / Presets',
    footerSlot: 'Policy State',
    description: 'Default screen edge attenuation and atmospheric lighting parameters.',
  },
  {
    id: 'allow-player-camera-override',
    label: 'Allow Player Camera Override',
    section: 'camera',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'File / Apply',
    footerSlot: 'Override State / Save',
    description: 'Permits players to toggle local custom camera styles in Options.',
  },
  {
    id: 'authored-map-camera-authority',
    label: 'Authored Map Camera Authority',
    section: 'camera',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'File / Apply',
    footerSlot: 'Override State / Save',
    description: 'Authored map definitions override global camera defaults when entering maps.',
  },

  // Releases
  {
    id: 'live-content-version',
    label: 'Live Content Version',
    section: 'releases',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'Releases / History',
    footerSlot: 'Live Version',
    description: 'Active database snapshot version currently serving players.',
  },
  {
    id: 'latest-snapshot',
    label: 'Latest Snapshot',
    section: 'releases',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'Releases / History',
    footerSlot: 'Snapshot',
    description: 'Most recent immutable point-in-time publication snapshot.',
  },
  {
    id: 'validation-result',
    label: 'Validation Result',
    section: 'releases',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'Validate',
    footerSlot: 'Validate',
    description: 'Automated orphan detection and template sanity check report.',
  },
  {
    id: 'snapshot-history-list',
    label: 'Snapshot History List',
    section: 'releases',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'History',
    footerSlot: 'Snapshot',
    description: 'Auditable archive of world and content release snapshots.',
  },
  {
    id: 'rollback-to-snapshot',
    label: 'Roll Back to Snapshot',
    section: 'releases',
    minPermission: 400,
    mode: 'native',
    isDestructive: true,
    toolbarSlot: 'History / Safety',
    footerSlot: 'Roll Back',
    description: 'Reverts the live world definitions back to an earlier verified snapshot.',
  },
  {
    id: 'publish-release-notes',
    label: 'Create Release Snapshot',
    section: 'releases',
    minPermission: 400,
    mode: 'native',
    toolbarSlot: 'Releases',
    footerSlot: 'Live Version / Save',
    description: 'Publishes the draft world content state into an immutable release.',
  },

  // Maintenance (1000+ Developer Only)
  {
    id: 'maintenance-profile-selection',
    label: 'Maintenance Profile Selection',
    section: 'maintenance',
    minPermission: 1000,
    mode: 'native',
    toolbarSlot: 'Actions',
    footerSlot: 'Run Action',
    description: 'Select execution scope (Auto, Quick sync, App rebuild, DB sync, Clean rebuild, Restart).',
  },
  {
    id: 'quick-sync-update',
    label: 'Quick Sync Update',
    section: 'maintenance',
    minPermission: 1000,
    mode: 'native',
    toolbarSlot: 'Actions',
    footerSlot: 'Run Action',
    description: 'Git pull + fast service restart (~5 seconds).',
  },
  {
    id: 'restart-only-action',
    label: 'Restart Services Only',
    section: 'maintenance',
    minPermission: 1000,
    mode: 'native',
    toolbarSlot: 'Actions',
    footerSlot: 'Run Action',
    description: 'Restarts Serapht.js, Go MMO, and Socket.io without code pull.',
  },
  {
    id: 'app-rebuild-action',
    label: 'Application Rebuild',
    section: 'maintenance',
    minPermission: 1000,
    mode: 'native',
    toolbarSlot: 'Actions',
    footerSlot: 'Run Action',
    description: 'Reinstalls npm dependencies and recompiles Serapht.js bundle.',
  },
  {
    id: 'db-sync-action',
    label: 'DB & Content Sync',
    section: 'maintenance',
    minPermission: 1000,
    mode: 'native',
    toolbarSlot: 'Actions',
    footerSlot: 'Run Action',
    description: 'Applies Prisma schema migrations and synchronizes game assets.',
  },
  {
    id: 'full-rebuild-action',
    label: 'Full Clean Rebuild',
    section: 'maintenance',
    minPermission: 1000,
    mode: 'native',
    isDestructive: true,
    toolbarSlot: 'Actions / Safety',
    footerSlot: 'Run Action',
    description: 'Exhaustive disk prune, fresh database migration, and full service recompilation.',
  },
  {
    id: 'keep-wipe-data-option',
    label: 'Data Retention Mode',
    section: 'maintenance',
    minPermission: 1000,
    mode: 'native',
    isDestructive: true,
    toolbarSlot: 'Safety',
    footerSlot: 'Environment / Run Action',
    description: 'Preserve gameplay state vs purge test records for a clean baseline.',
  },

  // Diagnostics
  {
    id: 'gateway-health-check',
    label: 'Gateway Health & Latency',
    section: 'diagnostics',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'Refresh / Filters',
    footerSlot: 'Last Check',
    description: 'End-to-end socket and REST latency checks for realm infrastructure.',
  },
  {
    id: 'realtime-bus-health',
    label: 'Realtime Bus Health',
    section: 'diagnostics',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'Refresh',
    footerSlot: 'Last Check',
    description: 'Socket.io and internal broadcast telemetry state.',
  },
  {
    id: 'publish-blockers',
    label: 'Publish Blockers & Orphans',
    section: 'diagnostics',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'Filters',
    footerSlot: 'Warning Count',
    description: 'Orphaned map links or template references requiring operator attention.',
  },

  // Staff Tools
  {
    id: 'map-announce',
    label: 'Broadcast Map Announcement',
    section: 'staff',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'minimal',
    footerSlot: 'Announce',
    description: 'Emits a high-priority system broadcast to all players in the active shard.',
  },
  {
    id: 'nearby-player-list',
    label: 'Active Players Roster',
    section: 'staff',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'Players',
    footerSlot: 'Players',
    description: 'Lists online players currently connected to the realm.',
  },
  {
    id: 'teleport-to-player',
    label: 'Teleport to Player',
    section: 'staff',
    minPermission: 200,
    mode: 'native',
    toolbarSlot: 'Support',
    footerSlot: 'Players / Support',
    description: 'Instant moderator jump to player coordinates.',
  },
  {
    id: 'kick-player',
    label: 'Remove Player from Map',
    section: 'staff',
    minPermission: 400,
    mode: 'native',
    isDestructive: true,
    toolbarSlot: 'Support / Safety',
    footerSlot: 'Support',
    description: 'Forces disconnect of player from live realm session.',
  },

  // Link-Outs
  {
    id: 'link-game-ops',
    label: 'Open Full Game Operations',
    section: 'staff',
    minPermission: 1000,
    mode: 'link',
    linkUrl: '/admin/game',
    toolbarSlot: 'Quick Actions',
    footerSlot: 'Open Full Admin',
  },
  {
    id: 'link-gateway-mgr',
    label: 'Open Gateway Management',
    section: 'realm',
    minPermission: 400,
    mode: 'link',
    linkUrl: '/admin/game/gates',
    toolbarSlot: 'Quick Actions',
    footerSlot: 'Open Full Admin',
  },
  {
    id: 'link-game-servers',
    label: 'Open Game Servers',
    section: 'diagnostics',
    minPermission: 400,
    mode: 'link',
    linkUrl: '/admin/game-servers',
    toolbarSlot: 'View / Logs',
    footerSlot: 'Open Full Admin',
  },
  {
    id: 'link-system-state',
    label: 'Open System State',
    section: 'diagnostics',
    minPermission: 1000,
    mode: 'link',
    linkUrl: '/admin/dev/system',
    toolbarSlot: 'View / Logs',
    footerSlot: 'Open Full Diagnostics',
  },
];
